/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/z/local"
#define EXEC_PREFIX "/home/z/local"
#define BINDIR "/home/z/local/bin"
#define SBINDIR "/home/z/local/sbin"
#define LIBEXECDIR "/home/z/local/libexec"
#define DATAROOTDIR "/home/z/local/share"
#define DATADIR "/home/z/local/share"
#define SYSCONFDIR "/home/z/local/etc"
#define SHAREDSTATEDIR "/home/z/local/com"
#define LOCALSTATEDIR "/home/z/local/var"
#define RUNSTATEDIR "/home/z/local/var/run"
#define INCLUDEDIR "/home/z/local/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/z/local/share/doc/bison"
#define INFODIR "/home/z/local/share/info"
#define HTMLDIR "/home/z/local/share/doc/bison"
#define DVIDIR "/home/z/local/share/doc/bison"
#define PDFDIR "/home/z/local/share/doc/bison"
#define PSDIR "/home/z/local/share/doc/bison"
#define LIBDIR "/home/z/local/lib"
#define LISPDIR "/home/z/local/share/emacs/site-lisp"
#define LOCALEDIR "/home/z/local/share/locale"
#define MANDIR "/home/z/local/share/man"
#define PKGDATADIR "/home/z/local/share/bison"
#define PKGINCLUDEDIR "/home/z/local/include/bison"
#define PKGLIBDIR "/home/z/local/lib/bison"
#define PKGLIBEXECDIR "/home/z/local/libexec/bison"
